In [1]:
import pandas as pd
import os
import re
import unidecode 
import difflib

In [2]:
files = os.listdir('./data/')

In [3]:
df = []
for i, file in enumerate(files):
    print('Processing file:', i+1, '... '+ str(len(files)))
    df_tmp = pd.read_csv('./data/' + file)
    df.append(df_tmp)

Processing file: 1 ... 30
Processing file: 2 ... 30
Processing file: 3 ... 30
Processing file: 4 ... 30
Processing file: 5 ... 30
Processing file: 6 ... 30
Processing file: 7 ... 30
Processing file: 8 ... 30
Processing file: 9 ... 30
Processing file: 10 ... 30
Processing file: 11 ... 30
Processing file: 12 ... 30
Processing file: 13 ... 30
Processing file: 14 ... 30
Processing file: 15 ... 30
Processing file: 16 ... 30
Processing file: 17 ... 30
Processing file: 18 ... 30
Processing file: 19 ... 30
Processing file: 20 ... 30
Processing file: 21 ... 30
Processing file: 22 ... 30
Processing file: 23 ... 30
Processing file: 24 ... 30
Processing file: 25 ... 30
Processing file: 26 ... 30
Processing file: 27 ... 30
Processing file: 28 ... 30
Processing file: 29 ... 30
Processing file: 30 ... 30

In [4]:
df = pd.concat(df, ignore_index=True)

In [5]:
df.head()

,tweet_id,text,favorite_count,retweet_count,created_at,source,reply_to_status,reply_to_user,retweets,favorites,keyword
0,1525888136483676162,rt @vladi_villegasp: vamos a presenciar el in...,0,194,2022-05-15 17:17:36+00:00,Twitter for Android,NaN,NaN,194,0,ciclo ruta
1,1525882983726477312,rt @grupo_energie: continuando con nuestro cic...,0,4,2022-05-15 16:57:07+00:00,Twitter for Android,NaN,NaN,4,0,ciclo ruta
2,1525882562823921665,rt @grupo_energie: continuando con nuestro cic...,0,4,2022-05-15 16:55:27+00:00,Twitter for iPhone,NaN,NaN,4,0,ciclo ruta
3,1525878640365412353,nena me voy a comprar una bici para hacer la c...,1,1,2022-05-15 16:39:51+00:00,Twitter for Android,NaN,NaN,1,1,ciclo ruta
4,1525827649310007297,rt @vladi_villegasp: vamos a presenciar el in...,0,194,2022-05-15 13:17:14+00:00,Twitter for Android,NaN,NaN,194,0,ciclo ruta

In [6]:
len(df)

3000

In [7]:
df

,tweet_id,text,favorite_count,retweet_count,created_at,source,reply_to_status,reply_to_user,retweets,favorites,keyword
0,1525888136483676162,rt @vladi_villegasp: vamos a presenciar el in...,0,194,2022-05-15 17:17:36+00:00,Twitter for Android,NaN,NaN,194,0,ciclo ruta
1,1525882983726477312,rt @grupo_energie: continuando con nuestro cic...,0,4,2022-05-15 16:57:07+00:00,Twitter for Android,NaN,NaN,4,0,ciclo ruta
2,1525882562823921665,rt @grupo_energie: continuando con nuestro cic...,0,4,2022-05-15 16:55:27+00:00,Twitter for iPhone,NaN,NaN,4,0,ciclo ruta
3,1525878640365412353,nena me voy a comprar una bici para hacer la c...,1,1,2022-05-15 16:39:51+00:00,Twitter for Android,NaN,NaN,1,1,ciclo ruta
4,1525827649310007297,rt @vladi_villegasp: vamos a presenciar el in...,0,194,2022-05-15 13:17:14+00:00,Twitter for Android,NaN,NaN,194,0,ciclo ruta
...,...,...,...,...,...,...,...,...,...,...,...
2995,1525869907384184832,RT @luciabastidasu: #VentanasRotas\n\n#Ventana...,0,21,2022-05-15 16:05:09+00:00,Twitter for iPhone,NaN,NaN,21,0,SectorMovilidad
2996,1525869149272309761,@VentanillaMov @SectorMovilidad Buen día neces...,0,0,2022-05-15 16:02:09+00:00,Twitter for Android,1.525504e+18,VentanillaMov,0,0,SectorMovilidad
2997,1525868860695400450,🚨Cambian las paradas de los servicios A52 y D2...,0,0,2022-05-15 16:01:00+00:00,Twitter Web App,NaN,NaN,0,0,SectorMovilidad
2998,1525867832017305600,RT @luciabastidasu: #VentanasRotas\n\n#Ventana...,0,21,2022-05-15 15:56:55+00:00,Twitter for Android,NaN,NaN,21,0,SectorMovilidad
2999,1525867577095888902,RT @luciabastidasu: #VentanasRotas\n\n#Ventana...,0,21,2022-05-15 15:55:54+00:00,Twitter Web App,NaN,NaN,21,0,SectorMovilidad

# Clean Data

In [8]:
df.drop_duplicates(subset=['tweet_id', 'text'], keep='last', inplace=True, ignore_index=True)
len(df)

910

In [9]:
df['txt'] = df['text'].str.lower()
df['txt'] = df['txt'].str.replace('co','')
df['txt'] = df['txt'].str.replace('ciclo ruta','ciclorruta')

In [10]:
def clean_txt(txt):  
    clean = ' '.join(re.findall('[^!,.¿? ]+', txt))
    clean = re.sub(r'#\S+', '', clean)
    #clean = re.sub(r"http\S+", "", clean)
    clean = re.sub(r'RT', '', clean)
    clean = re.sub(r'rt', '', clean)
    #clean = re.sub(r'@\S+', '', clean)
    clean = unidecode.unidecode(clean)
    #clean = re.sub(r'https', '', clean)
    #clean = re.sub(r'http\S+', '', clean)
    #clean = re.sub(r'^https?:\/\/.*[\r\n]*', '', clean, flags=re.MULTILINE)
    #clean = re.sub(r'\w+:\/{2}[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*', '', clean)
    clean = re.sub(r'/\S+', '', clean)
    clean = re.sub(r"http\S+", "", clean)
    #clean = re.sub(r"https\S+", "", clean)
    #clean = re.sub(r'@\S+', '', clean)
    
    clean = re.sub(r'@\S+', '', clean)
    clean = re.sub(r'co', '', clean)
    #clean = re.sub(r"[^a-zA-Z0-9]+", ' ', clean)
    #clean = re.sub(r"[-()\"#/@;:<>{}`+=~|.!?,]", "", clean)
    clean = re.sub(r'\W+', ' ', clean)
    return clean

In [11]:
def clean_txt(txt):  
    clean = ' '.join(re.findall('[^!,.¿? ]+', txt))
    clean = re.sub(r'rt', '', clean)
    clean = re.sub(r'@\S+', '', clean)
    clean = re.sub(r'#\S+', '', clean)
    clean = re.sub(r"http\S+", "", clean)
    clean = re.sub(r'/\S+', '', clean)
    clean = re.sub(r'\W+', ' ', clean)
    clean = unidecode.unidecode(clean)
    clean = clean.lstrip()
    clean = clean.rstrip()
    return clean

In [12]:
df['txt'] = df['txt'].str.replace('ciclo ruta','ciclorruta')
df['txt'] = df['txt'].str.replace('pi','pico')
df['txt'] = df.txt.apply(clean_txt)
df.txt.apply(clean_txt)

0      vamos a presenciar el inicio de un nuevo ciclo...
1      ntinuando n nuestro ciclo de mesas del proyect...
2                        puros alemanes en la ciclorruta
3      vamos a presenciar el inicio de un nuevo ciclo...
4      vamos a presenciar el inicio de un nuevo ciclo...
                             ...
905    este es el panorama en la carrera 75 en el sec...
906    buen dia necesito el recibo o factura para pag...
907    cambian las paradas de los servicios a52 y d22...
908    este es el panorama en la carrera 75 en el sec...
909    este es el panorama en la carrera 75 en el sec...
Name: txt, Length: 910, dtype: object

In [13]:
df.txt

0      vamos a presenciar el inicio de un nuevo ciclo...
1      ntinuando n nuestro ciclo de mesas del proyect...
2                        puros alemanes en la ciclorruta
3      vamos a presenciar el inicio de un nuevo ciclo...
4      vamos a presenciar el inicio de un nuevo ciclo...
                             ...
905    este es el panorama en la carrera 75 en el sec...
906    buen dia necesito el recibo o factura para pag...
907    cambian las paradas de los servicios a52 y d22...
908    este es el panorama en la carrera 75 en el sec...
909    este es el panorama en la carrera 75 en el sec...
Name: txt, Length: 910, dtype: object

In [14]:
"""thr = 0.95
df['Flag'] = 0
for text in df['txt'].tolist():
    df['temp'] = [difflib.SequenceMatcher(None, text1,text).ratio() for text1 in df['text'].tolist()]
    df.loc[df['temp'].gt(thr),['Flag']] = df['Flag'].max()+1#df.drop('temp',1)
    df.loc[~df['Flag'].duplicated(keep='first')]
df.drop('temp',1)
#df.loc[~df['Flag'].duplicated(keep='first')]
#len(df.loc[~df['Flag'].duplicated(keep='first')])
"""

"thr = 0.95\ndf['Flag'] = 0\nfor text in df['txt'].tolist():\n    df['temp'] = [difflib.SequenceMatcher(None, text1,text).ratio() for text1 in df['text'].tolist()]\n    df.loc[df['temp'].gt(thr),['Flag']] = df['Flag'].max()+1#df.drop('temp',1)\n    df.loc[~df['Flag'].duplicated(keep='first')]\ndf.drop('temp',1)\n#df.loc[~df['Flag'].duplicated(keep='first')]\n#len(df.loc[~df['Flag'].duplicated(keep='first')])\n"

In [15]:
df

,tweet_id,text,favorite_count,retweet_count,created_at,source,reply_to_status,reply_to_user,retweets,favorites,keyword,txt
0,1525185062156873730,rt @vladi_villegasp: vamos a presenciar el in...,0,194,2022-05-13 18:43:50+00:00,Twitter Web App,NaN,NaN,194,0,ciclo ruta,vamos a presenciar el inicio de un nuevo ciclo...
1,1525184470680162309,rt @grupo_energie: continuando con nuestro cic...,0,4,2022-05-13 18:41:29+00:00,Twitter for iPhone,NaN,NaN,4,0,ciclo ruta,ntinuando n nuestro ciclo de mesas del proyect...
2,1525904020979830792,@fotomultasocial @transitobucara puros alemane...,0,0,2022-05-15 18:20:43+00:00,Twitter for Android,1.525903e+18,FotoMultaSocial,0,0,ciclo ruta,puros alemanes en la ciclorruta
3,1525897380993835008,rt @vladi_villegasp: vamos a presenciar el in...,0,195,2022-05-15 17:54:20+00:00,Twitter for Android,NaN,NaN,195,0,ciclo ruta,vamos a presenciar el inicio de un nuevo ciclo...
4,1525888136483676162,rt @vladi_villegasp: vamos a presenciar el in...,0,195,2022-05-15 17:17:36+00:00,Twitter for Android,NaN,NaN,195,0,ciclo ruta,vamos a presenciar el inicio de un nuevo ciclo...
...,...,...,...,...,...,...,...,...,...,...,...,...
905,1525869907384184832,RT @luciabastidasu: #VentanasRotas\n\n#Ventana...,0,21,2022-05-15 16:05:09+00:00,Twitter for iPhone,NaN,NaN,21,0,SectorMovilidad,este es el panorama en la carrera 75 en el sec...
906,1525869149272309761,@VentanillaMov @SectorMovilidad Buen día neces...,0,0,2022-05-15 16:02:09+00:00,Twitter for Android,1.525504e+18,VentanillaMov,0,0,SectorMovilidad,buen dia necesito el recibo o factura para pag...
907,1525868860695400450,🚨Cambian las paradas de los servicios A52 y D2...,0,0,2022-05-15 16:01:00+00:00,Twitter Web App,NaN,NaN,0,0,SectorMovilidad,cambian las paradas de los servicios a52 y d22...
908,1525867832017305600,RT @luciabastidasu: #VentanasRotas\n\n#Ventana...,0,21,2022-05-15 15:56:55+00:00,Twitter for Android,NaN,NaN,21,0,SectorMovilidad,este es el panorama en la carrera 75 en el sec...
909,1525867577095888902,RT @luciabastidasu: #VentanasRotas\n\n#Ventana...,0,21,2022-05-15 15:55:54+00:00,Twitter Web App,NaN,NaN,21,0,SectorMovilidad,este es el panorama en la carrera 75 en el sec...

In [16]:
df['txt'][0][:int(len(df['txt'][0])*0.8)]

'vamos a presenciar el inicio de un nuevo ciclo de persecucion politica en venezuela esta es '

In [17]:
def redu(txt):
    return txt[:int(len(txt)*0.8)]

In [18]:
#df.txt.apply(redu)

In [19]:
#df['redu'] = df.txt.apply(redu)

In [20]:
len(df)

910

In [21]:
#df.drop_duplicates(subset=['redu'], keep='last', inplace=True, ignore_index=True)

In [22]:
len(df)

910

# Save Data

In [23]:
textfile = open("./data_training/data.txt", "w", encoding='utf-8')
for element in list(df['txt']):
    textfile.write(element + "\n")
textfile.close()

In [24]:
df.to_csv('./data_training/df.csv', index=False)